export const CATEGORY = {
    'По времени суток' : {
       "Завтрак" : "na-zavtrak",
       "Обед" :'supj',
       "Второе/Ужин" : 'vtoroe-bludo',
    },
    'Сладкое' : {
        "Торты" : 'tortj',
        "Десерты" : 'desert',
        "Выпечка" : 'vjpechka'
    },
    'Национальная кухня' : {
       "Азиатская": 'aziatskaya-kuxnya',
       "Татарская": 'tatarskaya-kuxnya',
       "Максиканская": 'meksikanskaya-kuxnya',
       "Индийская": 'indiiskaya-kuxnya',
       "Немецкая": 'nemetskaya-kuxnya',
       "Английская": 'angliiskaya-kuxnya',
       "Украинская": 'ukrainskaya-kuxnya',
       "Американская": 'amerikanskaya-kuxnya',
       "Еврейская": 'evreiskaya-kuxnya',
       "Средиземноморская": 'sredizemnomorskaya-kuxnya',
       "Болгарская": 'bolgarskaya-kuxnya',
       "Голандская": 'gollandskaya-kuxnya',
       "Польская": 'polskaya-kuxnya',
       "Молдавская": 'moldavskaya-kuxnya',
       "Литовская": 'litovskaya-kuxnya',
       "Чешская": 'cheshskaya-kuxnya',
       "Арабская": 'arabskaya-kuxnya',
       "Шведская": 'shvedskaya-kuxnya',
       "Венгерская": 'vengerskaya-kuxnya',
       "Финская": 'finskaya-kuxnya',
       "Белорусская": 'belorusskaya-kuxnya',
       "Бразильская": 'brazilskaya-kuxnya',
       "Португальская": 'portugalskaya-kuxnya',
       "Румынская": 'rumjnskaya-kuxnya',
       "Естонская": 'estonskaya-kuxnya',
       "Норвежская": 'norvezhskaya-kuxnya',
       "Австрийская": 'avstraliiskaya-kuxnya',
       "Ирландская": 'irlandskaya-kuxnya',
       "Кубинская": 'kubinskaya-kuxnya',
       "Аргентийская": 'argentinskaya-kuxnya',
       "Шотландская": 'shotlandskaya-kuxnya',
       "Гавайская": 'gavaiskaya-kuxnya',
       "Датская": 'datskaya-kuxnya',
       "Латышская": 'latjshskaya-kuxnya',
       "Русская": 'russkaya-kuxnya',
       "Французкая": 'frantsuzskaya-kuxnya',
       "Турецкая": 'turetskaya-kuxnya',
       "Кавказкая": 'kavkazskaya-kuxnya',
       "Классическая": 'klassicheskie-recepty-blud',
    },
    'Напитки' : 'napitki',
    'Гарниры' : 'garnirj',
    'Закуски' :  'zakuski',
    'Быстро и вкусно' : 'bjstro-i-vkusno',
    'Крупа' : 'krupa-i-krupyanje-izdeliya',
}